import type { WorkItem, Cycle } from '@coastal-ai/core/architect/types'

export interface PRCreationInput {
  workItem: WorkItem
  cycle: Cycle
  branchName: string
  planText: string
  diffText: string
  testSummary: string
  modelUsed: string
  commitAndPush: (message: string, branchName: string) => Promise<void>
  createPR: (opts: {
    title: string; body: string; branchName: string; draft: boolean
  }) => Promise<{ prUrl: string; prNumber: number }>
  commentOnIssue?: (issueRef: string, comment: string) => Promise<void>
}

export type PRCreationResult =
  | { kind: 'ok'; prUrl: string; prNumber: number }
  | { kind: 'hard_fail'; failureKind: 'env_push' | 'env_gh'; message: string }

export async function runPRCreationStage(input: PRCreationInput): Promise<PRCreationResult> {
  const { workItem, cycle, branchName, planText, testSummary, modelUsed } = input

  const commitMsg = [
    `chore(architect): ${workItem.title}`,
    '',
    `Work item: ${workItem.id}`,
    `Iteration: ${cycle.iteration}`,
    '',
    `Co-Authored-By: coastal-architect <bot@coastal.ai>`,
    `Architect-Cycle: ${cycle.id}`,
  ].join('\n')

  try {
    await input.commitAndPush(commitMsg, branchName)
  } catch (err: unknown) {
    const message = err instanceof Error ? err.message : String(err)
    return { kind: 'hard_fail', failureKind: 'env_push', message }
  }

  const prBody = buildPRBody({ workItem, cycle, planText, testSummary, modelUsed })
  const draft = workItem.approvalPolicy === 'full'

  try {
    const { prUrl, prNumber } = await input.createPR({
      title: `[architect] ${workItem.title}`,
      body: prBody,
      branchName,
      draft,
    })

    if (workItem.source === 'github' && workItem.sourceRef && input.commentOnIssue) {
      try {
        await input.commentOnIssue(workItem.sourceRef, `Architect opened PR #${prNumber}: ${prUrl}`)
      } catch { /* non-fatal */ }
    }

    return { kind: 'ok', prUrl, prNumber }
  } catch (err: unknown) {
    const message = err instanceof Error ? err.message : String(err)
    return { kind: 'hard_fail', failureKind: 'env_gh', message }
  }
}

function buildPRBody(opts: {
  workItem: WorkItem; cycle: Cycle; planText: string; testSummary: string; modelUsed: string
}): string {
  const { workItem, cycle, planText, testSummary, modelUsed } = opts
  return [
    `## Plan`, '', planText, '',
    `## Test Summary`, '', testSummary, '',
    `## Metadata`, '',
    `| Field | Value |`, `|---|---|`,
    `| Work Item | \`${workItem.id}\` |`,
    `| Source | ${workItem.source} |`,
    `| Iteration | ${cycle.iteration} |`,
    `| Model | ${modelUsed} |`,
    `| Cycle | \`${cycle.id}\` |`,
    '', `---`, `*Generated by coastal-architect*`,
  ].join('\n')
}
